website/models.py
from . import db
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class Customer(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True, nullable=False)
    username = db.Column(db.String(150), unique=True, nullable=False)   
    password_hash = db.Column(db.String(150), nullable=False)
    date_joined = db.Column(db.DateTime, default=datetime.utcnow)

    cart_items = db.relationship('Cart', backref=db.backref('customer', lazy=True))
    orders = db.relationship('Order', backref=db.backref('customer'), lazy=True)

    @property
    def password(self): 
        raise AttributeError('Password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password=password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __str__(self):
        return '<Customer %r>' % Customer.id


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(150), nullable = False)
    current_price = db.Column(db.Float, nullable = False)
    previous_price = db.Column(db.Float, nullable = False)
    in_stock = db.Column(db.Integer, nullable = False)
    product_picture = db.Column(db.String(1000), nullable = False)
    flash_sale = db.Column(db.Boolean, default = False)
    date_added = db.Column(db.DateTime, default=datetime.utcnow)

    carts = db.relationship('Cart', backref=db.backref('product', lazy=True))
    orders = db.relationship('Order', backref=db.backref('product'), lazy=True)

    def __str__(self):
        return '<Product %r>' % self.product_name

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.Integer, nullable = False)

    customer_link = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable = False)
    product_link = db.Column(db.Integer, db.ForeignKey('product.id'), nullable = False)

    #customer product

    def __str__(self):
        return '<Cart %r>' % self.id

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.Integer, nullable = False)
    price = db.Column(db.Float, nullable = False)
    status = db.Column(db.String(100), nullable = False)
    payment_id = db.Column(db.String(1000), nullable = False)

    customer_link = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable = False)
    product_link = db.Column(db.Integer, db.ForeignKey('product.id'), nullable = False)

    #customer
    def __str__(self):
        return '<Order %r>' % self.id

website/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, IntegerField, FloatField, EmailField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo

# User authentication forms

class SignUpForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    password1 = PasswordField('Enter Your Password', validators=[DataRequired(), Length(min=6)])
    password2 = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=6), EqualTo('password1', message='Passwords must match')])
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, login_manager

db = SQLAlchemy()
DB_NAME = 'database_sqlite3'

def create_database():
    db.create_all()
    print('Database created!')

# initialize app
def create_app():
    app = Flask(__name__)
    # encrypting session data
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)

    login_manager = LoginManager() # keep track of user sessions and access tokens
    login_manager.init_app(app) # initialize login manager
    login_manager.login_view = 'auth.login' # redirect to login page if user is not logged in

    @login_manager.user_loader
    def load_user(id):
        return Customer.query.get(int(id))

    # register blueprints
    from .views import views
    from .auth import auth
    from .admin import admin
    from .models import Customer, Cart, Product, Order

    app.register_blueprint(views, url_prefix='/') # localhost:5500/about-us
    app.register_blueprint(auth, url_prefix='/') # localhost:5500/auth/change-password
    app.register_blueprint(admin, url_prefix='/')

    with app.app_context():
        create_database()
        
    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .forms import LoginForm, SignUpForm
from .models import Customer
from flask_login import login_user, login_required, logout_user
from . import db

auth = Blueprint('auth', __name__)


@auth.route('/signup', methods=['GET', 'POST'])
def sign_up():
    form = SignUpForm()
    if form.validate_on_submit():  # Validate form submission
        email = form.email.data
        username = form.username.data
        password1 = form.password1.data
        password2 = form.password2.data

        if password1 == password2:
            new_customer = Customer()
            new_customer.email = email
            new_customer.username = username
            new_customer.password = password2
            
            try:
                db.session.add(new_customer)
                db.session.commit()
                flash('Account created successfully! You can now log in.', 'success')
                return redirect(url_for('auth.login'))
            except Exception as e:
                print(e)
                flash('An error occurred. Please try again.', 'danger')

            form.email.data = ''
            form.username.data = ''
            form.password1.data = ''
            form.password2.data = ''

    return render_template('signup.html', form=form) 

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():  # Validate form submission
        username = form.username.data
        password = form.password.data
        # Check if user exists
        customer = Customer.query.filter_by(username=username).first()
        if customer:
            if customer.verify_password(password=password):
                login_user(customer)
                flash('Logged in successfully!', 'success')
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect username or password. Please try again.', 'danger')
        else:
            flash('Account does not exist. Please sign up.', 'danger')
    return render_template('login.html', form=form)

@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('Logged out successfully!', 'success')
    return redirect(url_for('views.home'))

@auth.route('/profile/<int:customer_id>', methods=['GET', 'POST'])
@login_required
def profile(customer_id):
    customer = Customer.query.get(customer_id)
    return render_template('profile.html', customer=customer)

website/views.py
from flask import Blueprint, render_template

# routes or url endpoints
views = Blueprint('views', __name__)

# decorator to build a function to a url endpoint
@views.route('/')
def home():
    return render_template('index.html')

website/templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pixiewire Co | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="../static/css/formstyles.css">

    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Pixiewire Co</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="../static/css/styles.css">
        <title>Pixiewire Co | {% block title %} {% endblock %}</title>
    </head>
    <body>
        <header>
            <input type="checkbox" name="" id="toggler">
            <label for="toggler" class="fas fa-bars"></label>

            <a href="#" class="logo">Pixiewire<span>.</span>Co</a>

            <nav class="navbar">
                <a href="#home">Home</a>
                <a href="#about">About</a>
                <a href="#products">Products</a>
                <a href="#review">Review</a>
                <a href="#contact">Contact</a>
            </nav>

            <div class="search-bar">
                <i class="fas fa-search"></i>
                <input type=text placeholder="Search">
            </div>
            <div class="icons">
                <a href="#" class="fas fa-heart"></a>
                <a href="#" class="fas fa-shopping-cart"></a>
                <div class="dropdown" id="profileDropdown" data-bs-toggle="dropdown">
                    <a href="#" class="fas fa-user"></a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_authenticated %}
                        <li><a class="dropdown-item" href="/profile/{{ current_user.id }}">Profile <i class="fas fa-user"></i></a></li>
                        <li><a class="dropdown-item" href="#">Orders <i class="fas fa-truck"></i></a></li>
                        <li><a class="dropdown-item" href="/logout">Log Out <i class="fas fa-arrow-right"></i></a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="/login">Login <i class="fas fa-arrow-left"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </header>

        <section class="home" id="home">
            <div class="content">
                <h3>Digital Products</h3>
                <span>by pixiewire</span>
                <p>Sprinkle your day with pixie charm!</p>
                <a href="#" class="btn">Shop now</a>
            </div>
        </section>
        <section class="about" id="about">
            <h1 class="heading"> <span>⋆. 𐙚 ˚ About </span> Us ⋆. 𐙚 ˚</h1>

            <div class = "row">
                <div class="video-container">
                    <video src="../static/images/aboutvid.mp4" loop autoplay muted></video>
                    <h3>World's Best Digital Seller</h3>
                </div>

                <div class="content">
                    <h3>Why Choose Us?</h3>
                    <p>Because why not?</p>
                    <p>Just kidding :) At Pixiewire, we believe in adding a touch of magic to the digital world. We’re a creative hub for anyone who loves personalizing their digital spaces, whether you're a student, professional, or just someone who appreciates a bit of whimsy. Our range of high-quality digital products, from unique stickers to versatile templates, is designed to make your life more organized, inspired, and fun.

Each product is crafted with care and creativity, blending functionality with aesthetic appeal. We’re passionate about helping you express yourself in your own style, so our designs are as unique and varied as the people who use them.

Thank you for stopping by! We hope Pixiewire becomes your go-to place for all things digital and delightful. 
                    </p>
                    <a href="#" class="btn">Learn more</a>
            </div>
        </section> 
        <section class="icons-container">
            <div class="icons">
                <img src="../static/images/trolley-cart.png" alt="">
                <div class="info">
                    <h3>Free Delivery</h3>
                    <span>On All Orders</span>
                </div>
            </div>
            <div class="icons">
                <img src="../static/images/left-arrow.png" alt="">
                <div class="info">
                    <h3>10 Days Returns</h3>
                    <span>Moneyback Guarantee</span>
                </div>
            </div>
            <div class="icons">
                <img src="../static/images/present.png" alt="">
                <div class="info">
                    <h3>Offer & Gifts</h3>
                    <span>On All Orders</span>
                </div>
            </div>
            <div class="icons">
                <img src="../static/images/credit-cards.png" alt="">
                <div class="info">
                    <h3>Secure Payments</h3>
                    <span>Protected By Paypal</span>
                </div>
            </div>
        </section>
        <section class="products" id="products">
            <h1 class="heading">⋆. 𐙚 ˚ Latest <span>Products ⋆. 𐙚 ˚</span> </h1>
            <div class = box-container>
                <div class="box">
                    <span class="discount">-30%</span>
                    <div class="image">
                        <img src="../static/images/cc-1.png" alt="">
                        <div class="icons">
                            <a href="#" class="fas fa-heart"></a>
                            <a href="#" class="cart-btn">add to cart</a>
                            <a href="#" class="fas fa-share"></a>
                        </div>
                    </div>
                    <div class="content">
                        <h3>Cottage Core Cute Digital Stickers Pack</h3>
                        <div class="price"> $1.80 <span>$2.58</span> </div>
                    </div>
                </div>
                <div class="box">
                    <span class="discount">-30%</span>
                    <div class="image">
                        <img src="../static/images/csa-1.png" alt="">
                        <div class="icons">
                            <a href="#" class="fas fa-heart"></a>
                            <a href="#" class="cart-btn">add to cart</a>
                            <a href="#" class="fas fa-share"></a>
                        </div>
                    </div>
                    <div class="content">
                        <h3>Computer Science Cute Digital Stickers Pack</h3>
                        <h4>Set A</h4>
                        <div class="price"> $1.80 <span>$2.58</span></div>
                    </div>
                </div>
                <div class="box">
                    <span class="discount">-30%</span>
                    <div class="image">
                        <img src="../static/images/csb-1.png" alt="">
                        <div class="icons">
                            <a href="#" class="fas fa-heart"></a>
                            <a href="#" class="cart-btn">add to cart</a>
                            <a href="#" class="fas fa-share"></a>
                        </div>
                    </div>
                    <div class="content">
                        <h3>Computer Science Cute Digital Stickers Pack</h3>
                        <h4>Set B</h4>
                        <div class="price"> $1.80 <span>$2.58</span> </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="review" id="review">
            <h1 class="heading">⋆. 𐙚 ˚ Customer's <span>Review ⋆. 𐙚 ˚</span> </h1>
            <div class="box-container">
                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae dolor accusamus enim ut odit, aliquam nesciunt eaque nulla dignissimos.</p>
                    <div class="user">
                        <img src="../static/images/buyer1.png" alt="">
                        <div class="user-info">
                            <h3>Andrea Jeon</h3>
                            <span>Happy Customer</span>
                         </div>   
                    </div>
                    <span class="fas fa-quote-right"></span>
                </div>
                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae dolor accusamus enim ut odit, aliquam nesciunt eaque nulla dignissimos.</p>
                    <div class="user">
                        <img src="../static/images/buyer1.png" alt="">
                        <div class="user-info">
                            <h3>Jungkook Jeon</h3>
                            <span>Happy Customer</span>
                         </div>   
                    </div>
                    <span class="fas fa-quote-right"></span>
                </div>
                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae dolor accusamus enim ut odit, aliquam nesciunt eaque nulla dignissimos.</p>
                    <div class="user">
                        <img src="../static/images/buyer1.png" alt="">
                        <div class="user-info">
                            <h3>Daniil Dubov</h3>
                            <span>Happy Customer</span>
                         </div>   
                    </div>
                    <span class="fas fa-quote-right"></span>
                </div>
            </div>
        </section>
        <section class="contact" id="contact">  
            <h1 class="heading"> <span>⋆. 𐙚 ˚ Contact</span> Us ⋆. 𐙚 ˚</h1>
            <div class="row">
                <form action="">
                    <input type="text" placeholder="Name" class="box">
                    <input type="email" placeholder="Email" class="box">
                    <input type="number" placeholder="Number" class="box">
                    <textarea name="" class="box" placeholder="Message" id="" cols="30" rows="10"></textarea>
                    <input type="submit" value="Send message" class="btn">
                </form>
                <div class="image">
                    <img src="../static/images/pixiewire.png" alt="">
                </div> 
            </div>
        </section>
        <section class="footer">
            <div class="box-container">
                <div class="box">
                    <h3>Quick Links</h3>
                    <a href="#">Home</a>
                    <a href="#">About</a>
                    <a href="#">Products</a>
                    <a href="#">Review</a>
                </div>
                <div class="box">
                    <h3>Extra Links</h3>
                    <a href="#">My Account</a>
                    <a href="#">My Orders</a>
                    <a href="#">My Favorites</a>
                </div>
                <div class="box">
                    <h3>Locations</h3>
                    <a href="#">Philippines</a>
                </div>
                <div class="box">
                    <h3>Contact Info</h3>
                    <a href="#">+639453066928</a>
                    <a href="#">pixiewired@gmail.com</a>
                    <a href="#">Aklan, Philippines</a>
                    <img src="../static/images/paypal.png" alt="">
                    <img src="../static/images/gcash.png" alt="">
                </div>
            </div>

            <div class="credit">Created by <span>Pixiewire</span> | All Rights Reserved</div>
        </section>
    
    <script src="../static/js/myscripts.js"></script>
    </body>
</html>

website/templates/login.html
{% extends "forms.html" %}
{% block title %}Login{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}  

{% block body %}
    <div class="wrapper">
        <form action="/login" method="post" action="{{ url_for('auth.login') }}">
            {{ form.hidden_tag() }}
            <h1>Login</h1>
            <div class="input-box">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
                <i class="fas fa-user"></i>
            </div>

            <div class="input-box">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
                <i class="fas fa-lock"></i>
            </div>

            <div class="remember-forgot">
                <label><input type="checkbox"> Remember me</label>
                <a href="#">Forgot password?</a>
            </div>

            <button type="submit" class="btn">Login</button>

            <div class="register-link">
                <p>Don't have an account? <a href="{{ url_for('auth.sign_up') }}">Register</a></p>
            </div>
    </div>
{% endblock %}

website/templates/profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Pixiewire Co</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="../static/css/styles.css">
        <title>Pixiewire Co | {% block title %} {% endblock %}</title>
    </head>
    <body>
        <header>
            <input type="checkbox" name="" id="toggler">
            <label for="toggler" class="fas fa-bars"></label>

            <a href="#" class="logo">Pixiewire<span>.</span>Co</a>

            <nav class="navbar">
                <a href="#home">Home</a>
                <a href="#about">About</a>
                <a href="#products">Products</a>
                <a href="#review">Review</a>
                <a href="#contact">Contact</a>
            </nav>

            <div class="search-bar">
                <i class="fas fa-search"></i>
                <input type=text placeholder="Search">
            </div>
            <div class="icons">
                <a href="#" class="fas fa-heart"></a>
                <a href="#" class="fas fa-shopping-cart"></a>
                <div class="dropdown" id="profileDropdown" data-bs-toggle="dropdown">
                    <a href="#" class="fas fa-user"></a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_authenticated %}
                        <li><a class="dropdown-item" href="/profile/{{ current_user.id }}">Profile <i class="fas fa-user"></i></a></li>
                        <li><a class="dropdown-item" href="#">Orders <i class="fas fa-truck"></i></a></li>
                        <li><a class="dropdown-item" href="/logout">Log Out <i class="fas fa-arrow-right"></i></a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="/login">Login <i class="fas fa-arrow-left"></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </header>
        <section class="profile" id="profile">
            <h1 class="heading"> <span>⋆. 𐙚 ˚ profile ⋆. 𐙚 ˚</span> </h1>
            <div class="row">
                <div class="image">
                    <img src="../static/images/pixiewire.png" alt="">
                </div>  
                <div class="content">
                    <h3>username : {{ current_user.username }}</h3>
                    <p>email : {{ current_user.email }}</p>
                </div>
            </div>
        </section>
                    

website/templates/signup.html
{% extends 'forms.html' %}
{% block title %}Sign Up{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}  

{% block body %}
<section class="auth-form">
    <div class="wrapper">
        <form method="post" action="{{ url_for('auth.sign_up') }}">
            {{ form.hidden_tag() }}
            <h1>Sign Up</h1>

            <div class="input-box">
                {{ form.email.label }}
                {{ form.email(class="form-control") }}
                <i class="fas fa-envelope"></i>
            </div>

            <div class="input-box">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
                <i class="fas fa-user"></i>
            </div>

            <div class="input-box">
                {{ form.password1.label }}
                {{ form.password1(class="form-control") }}
                <i class="fas fa-lock"></i>
            </div>

            <div class="input-box">
                {{ form.password2.label }}
                {{ form.password2(class="form-control") }}
                <i class="fas fa-lock"></i>
            </div>

            <button type="submit" class="btn">Sign Up</button>

            <div class="register-link">
                <p>Already have an account? <a href="{{ url_for('auth.login') }}">Log In</a></p>
            </div>
        </form>
    </div>
</section>
{% endblock %}